version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c 'composer install --ignore-platform-reqs --no-ansi --no-interaction --no-scripts && php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_ROOT: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306


    testdb:
        platform: linux/x86_64
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_ROOT: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/testdbdata:/var/lib/mysql
        ports:
            - 3307:3306
